name: Deploy PD Infojobs ChatGPT Plugin

on:
    push:
        branches: [main]

jobs:
    Deploy:
        runs-on: ubuntu-latest

        steps:
            - name: ENTRECOT DEPLOY
              uses: D3rHase/ssh-command-action@v0.2.2
              with:
                  host: ${{secrets.HOST}}
                  user: ${{secrets.USERNAME}}
                  private_key: ${{secrets.KEY}}
                  command: |
                      cd infojobs-chatgpt-plugin &&
                      git pull origin main &&
                      npm prune &&
                      npm install &&
                      pm2 restart infojobs-chatgpt-plugin
